import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import {
  Avatar, Box, Card, Typography, Table, TableBody, TableCell,
  TableContainer, TableHead, TableRow, Skeleton, Chip, IconButton, ListItemIcon, Menu, MenuItem
} from '@mui/material'
import MoreVertIcon from '@mui/icons-material/MoreVert'
import RequestQuoteIcon from '@mui/icons-material/RequestQuote'
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined'

import { fetchAllQuotations } from '@/api/serviceRequests'
import type { ServiceRequestQuotationList } from '@/api/serviceRequests'

const ACTION_MENU_PAPER = {
  sx: {
    borderRadius: '16px',
    minWidth: 170,
    boxShadow: '0 18px 45px rgba(30,27,75,0.16)',
    border: '1px solid #EEF0F6',
  },
}
const ACTION_MENU_ITEM = {
  py: 1.15,
  px: 1.5,
  mx: 0.75,
  borderRadius: '10px',
  fontWeight: 800,
}

const ServiceQuotationsList = () => {
  const navigate = useNavigate()
  const [actionAnchor, setActionAnchor] = useState<HTMLElement | null>(null)
  const [actionQuotation, setActionQuotation] = useState<ServiceRequestQuotationList | null>(null)

  const openActions = (event: React.MouseEvent<HTMLElement>, quotation: ServiceRequestQuotationList) => {
    event.stopPropagation()
    setActionAnchor(event.currentTarget)
    setActionQuotation(quotation)
  }

  const closeActions = () => {
    setActionAnchor(null)
    setActionQuotation(null)
  }

  const { data: quotations, isLoading } = useQuery({
    queryKey: ['service-quotations'],
    queryFn: fetchAllQuotations,
  })

  const formatDate = (d: string | null) => {
    if (!d) return '—'
    return new Date(d).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    })
  }

  return (
    <Box className="page-enter" sx={{ maxWidth: 1440, mx: 'auto' }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.6, mb: 3 }}>
        <Avatar sx={{ width: 52, height: 52, bgcolor: '#F0EDFF', color: '#6757D8', borderRadius: '18px' }}>
          <RequestQuoteIcon />
        </Avatar>
        <Box>
          <Typography variant="h5" sx={{ fontWeight: 900, color: '#1E1B4B' }}>
            Service Quotations
          </Typography>
          <Typography variant="body2" sx={{ color: '#8B95A7', fontWeight: 700 }}>
            View all service request quotations generated by admins.
          </Typography>
        </Box>
      </Box>

      <Card sx={{ overflow: 'hidden', borderRadius: '24px', border: '1px solid #EEF0F6', boxShadow: '0 18px 45px rgba(49,46,129,0.08)' }}>
        <TableContainer className="list-scroll-panel">
          <Table stickyHeader>
            <TableHead>
              <TableRow>
                <TableCell>Quotation #</TableCell>
                <TableCell>Request #</TableCell>
                <TableCell>Facility</TableCell>
                <TableCell>Amount</TableCell>
                <TableCell>Status</TableCell>
                <TableCell>Description</TableCell>
                <TableCell>Created Date</TableCell>
                <TableCell align="right">Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {isLoading
                ? Array.from({ length: 5 }).map((_, i) => (
                    <TableRow key={i}>
                      {Array.from({ length: 8 }).map((_, j) => (
                        <TableCell key={j}><Skeleton variant="text" /></TableCell>
                      ))}
                    </TableRow>
                  ))
                : !quotations || quotations.length === 0
                  ? (
                    <TableRow>
                      <TableCell colSpan={8} align="center" sx={{ py: 6 }}>
                        <Typography sx={{ color: '#6B7280', fontWeight: 500 }}>
                          No quotations found.
                        </Typography>
                      </TableCell>
                    </TableRow>
                  )
                  : quotations.map((q) => (
                      <TableRow
                        key={q.id}
                        sx={{
                          '&:hover': { backgroundColor: '#FAFAFF' },
                          cursor: 'pointer',
                        }}
                        onClick={() => navigate(`/service-requests/${q.service_request_id}`)}
                      >
                        <TableCell>
                          <Typography variant="body2" sx={{ fontWeight: 800, color: '#7161D8', fontFamily: 'monospace' }}>
                            {q.quotation_number || `Q-${q.id}`}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography variant="body2" sx={{ fontWeight: 800, color: '#6757D8', fontFamily: 'monospace' }}>
                            {q.request_number}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography variant="body2" sx={{ fontWeight: 500 }}>
                            {q.facility_name || '—'}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography variant="body2" sx={{ fontWeight: 700, color: '#10B981' }}>
                            ${Number(q.amount).toFixed(2)}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Chip label={q.status || 'draft'} size="small" sx={{ fontWeight: 600, fontSize: '0.7rem', textTransform: 'capitalize' }} />
                        </TableCell>
                        <TableCell>
                          <Typography
                            variant="body2"
                            sx={{
                              color: '#374151',
                              maxWidth: 250,
                              whiteSpace: 'nowrap',
                              overflow: 'hidden',
                              textOverflow: 'ellipsis'
                            }}
                          >
                            {q.description}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography variant="body2" sx={{ color: '#6B7280' }}>
                            {formatDate(q.created_at)}
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <IconButton
                            size="small"
                            onClick={(event) => openActions(event, q)}
                            sx={{ borderRadius: '12px', bgcolor: '#F3F4F6', color: '#6757D8', '&:hover': { bgcolor: '#EDE9FE' } }}
                          >
                            <MoreVertIcon fontSize="small" />
                          </IconButton>
                        </TableCell>
                      </TableRow>
                    ))}
            </TableBody>
          </Table>
        </TableContainer>
        <Menu anchorEl={actionAnchor} open={Boolean(actionAnchor)} onClose={closeActions} PaperProps={ACTION_MENU_PAPER}>
          {actionQuotation && (
            <MenuItem sx={ACTION_MENU_ITEM} onClick={() => { navigate(`/service-requests/${actionQuotation.service_request_id}`); closeActions() }}>
              <ListItemIcon><VisibilityOutlinedIcon fontSize="small" sx={{ color: '#6757D8' }} /></ListItemIcon>
              View Details
            </MenuItem>
          )}
        </Menu>
      </Card>
    </Box>
  )
}

export default ServiceQuotationsList
