"""Operation and permission extraction from the live FastAPI application.

The OpenAPI schema is generated by FastAPI from the same route handlers and
Pydantic models that serve production traffic, so an operation document can
never drift from the endpoint it describes.
"""
from __future__ import annotations

from typing import Any

from app.assistant.kb.documents import KBDocument
from app.assistant.kb.extractors import EXCLUDED_MODEL_FILES, humanize


# Path segment after the API prefix -> canonical business module.
PATH_MODULE_ALIASES: dict[str, str] = {
    "service-requests": "service-requests",
    "facility-users": "users",
    "equipment": "facilities",
    "modalities": "facilities",
    "tiers": "facilities",
    "facility-documents": "facilities",
    "inspection-forms": "inspections",
    "test-equipment": "inspections",
    "audit-logs": "audit",
    "invoices": "billing",
    "payments": "billing",
    "notifications": "platform",
    "calendar": "platform",
    "departments": "users",
}

# Assistant-invisible surfaces: private messaging, auth/token endpoints which
# must never be described as callable, infrastructure probes, and the
# unauthenticated client portal, which is a different audience entirely.
EXCLUDED_PATH_SEGMENTS: frozenset[str] = frozenset({
    "chat", "workspaces", "websocket", "ws", "auth", "login", "token",
    "health", "ready", "live", "metrics", "webhooks", "public", "client-sales",
})


def _module_for_path(path: str, api_prefix: str) -> str | None:
    trimmed = path[len(api_prefix):] if path.startswith(api_prefix) else path
    segments = [segment for segment in trimmed.split("/") if segment]
    if not segments:
        return None
    head = segments[0]
    if head in EXCLUDED_PATH_SEGMENTS:
        return None
    return PATH_MODULE_ALIASES.get(head, head)


def _resolve_ref(spec: dict[str, Any], ref: str) -> dict[str, Any]:
    node: Any = spec
    for part in ref.lstrip("#/").split("/"):
        if not isinstance(node, dict):
            return {}
        node = node.get(part, {})
    return node if isinstance(node, dict) else {}


def _request_fields(spec: dict[str, Any], operation: dict[str, Any]) -> tuple[list[str], list[str]]:
    """Return (required, optional) request-body field names for an operation."""
    body = operation.get("requestBody") or {}
    content = body.get("content") or {}
    json_schema = (content.get("application/json") or {}).get("schema") or {}
    if "$ref" in json_schema:
        json_schema = _resolve_ref(spec, json_schema["$ref"])
    properties = json_schema.get("properties") or {}
    if not properties:
        return [], []
    required = list(json_schema.get("required") or [])
    optional = [name for name in properties if name not in required]
    return sorted(required), sorted(optional)


def operation_documents(spec: dict[str, Any], api_prefix: str = "/api/v1") -> list[KBDocument]:
    """One document per module listing every operation it exposes.

    Grouping by module rather than emitting one document per route keeps
    retrieval coherent: a question about billing returns the billing operations
    together instead of a single orphaned endpoint.
    """
    by_module: dict[str, list[str]] = {}
    counts: dict[str, int] = {}

    for path, methods in sorted(spec.get("paths", {}).items()):
        module = _module_for_path(path, api_prefix)
        if module is None:
            continue
        for method, operation in sorted(methods.items()):
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            summary = (
                operation.get("summary")
                or (operation.get("description") or "").split("\n")[0]
                or ""
            ).strip()
            required, optional = _request_fields(spec, operation)
            lines = ["### `{} {}`".format(method.upper(), path)]
            if summary:
                lines.append(summary)
            if required:
                lines.append("- **Required:** " + ", ".join("`" + f + "`" for f in required))
            if optional:
                shown = optional[:14]
                suffix = "" if len(optional) <= 14 else ", and {} more".format(len(optional) - 14)
                lines.append(
                    "- **Optional:** " + ", ".join("`" + f + "`" for f in shown) + suffix
                )
            by_module.setdefault(module, []).append("\n".join(lines))
            counts[module] = counts.get(module, 0) + 1

    documents: list[KBDocument] = []
    for module, blocks in sorted(by_module.items()):
        body = (
            "## Operations\n"
            "Every API operation available in the " + module + " module. "
            "Each requires the matching module permission.\n\n"
            + "\n\n".join(blocks)
        )
        documents.append(KBDocument(
            doc_id="operations." + module,
            kind="operation",
            module=module,
            title="How to work with " + humanize(module),
            body=body,
            source="FastAPI OpenAPI schema",
            metadata={"module": module, "operation_count": counts[module]},
        ))
    return documents


def permission_documents() -> list[KBDocument]:
    """The role x module x action matrix, extracted from the canonical table."""
    from app.utils.permissions import ALL_MODULES, _ROLE_PERMISSIONS

    visible_modules = [m for m in ALL_MODULES if m not in EXCLUDED_MODEL_FILES and m != "chat"]

    header = "| Role | " + " | ".join(visible_modules) + " |"
    divider = "| --- |" + " --- |" * len(visible_modules)
    rows: list[str] = []
    for role, module_map in sorted(_ROLE_PERMISSIONS.items()):
        cells: list[str] = []
        for module in visible_modules:
            actions = module_map.get(module) or frozenset()
            cells.append(", ".join(sorted(actions)) if actions else "none")
        rows.append("| **" + role + "** | " + " | ".join(cells) + " |")

    matrix = KBDocument(
        doc_id="permission.matrix",
        kind="permission",
        module="users",
        title="Who can do what: role permission matrix",
        body=(
            "## Default permissions by role\n"
            "Default actions each role may perform per module. Per-user overrides "
            "stored on the user record take absolute precedence over these defaults.\n\n"
            "Actions are `index` (list), `view` (read one), `add`, `edit`, `delete`.\n\n"
            + header + "\n" + divider + "\n" + "\n".join(rows)
        ),
        source="app/utils/permissions.py::_ROLE_PERMISSIONS",
        metadata={"roles": sorted(_ROLE_PERMISSIONS.keys()), "modules": visible_modules},
    )
    return [matrix]
