"""Add revision_history

Revision ID: 03659694904d
Revises: 77ca0550e915
Create Date: 2026-05-06 21:53:45.881279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03659694904d'
down_revision: Union[str, Sequence[str], None] = '77ca0550e915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_request_quotations', sa.Column('revision_history', sa.JSON(), nullable=True))
    op.alter_column('service_request_quotations', 'quotation_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_service_request_quotations_quotation_number'), 'service_request_quotations', ['quotation_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_request_quotations_quotation_number'), table_name='service_request_quotations')
    op.alter_column('service_request_quotations', 'quotation_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('service_request_quotations', 'revision_history')
    # ### end Alembic commands ###
