"""Add revision_history

Revision ID: 03659694904d
Revises: 77ca0550e915
Create Date: 2026-05-06 21:53:45.881279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03659694904d'
down_revision: Union[str, Sequence[str], None] = '77ca0550e915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {
        column["name"]
        for column in inspector.get_columns("service_request_quotations")
    }

    if "revision_history" not in columns:
        op.add_column('service_request_quotations', sa.Column('revision_history', sa.JSON(), nullable=True))

    if "quotation_number" not in columns:
        op.add_column(
            "service_request_quotations",
            sa.Column("quotation_number", sa.String(), nullable=True),
        )
        op.execute(
            sa.text(
                "UPDATE service_request_quotations "
                "SET quotation_number = 'Q-' || id::text "
                "WHERE quotation_number IS NULL"
            )
        )

    op.alter_column('service_request_quotations', 'quotation_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    indexes = {
        index["name"]
        for index in sa.inspect(bind).get_indexes("service_request_quotations")
    }
    index_name = op.f('ix_service_request_quotations_quotation_number')
    if index_name not in indexes:
        op.create_index(index_name, 'service_request_quotations', ['quotation_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_request_quotations_quotation_number'), table_name='service_request_quotations')
    op.alter_column('service_request_quotations', 'quotation_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('service_request_quotations', 'revision_history')
    # ### end Alembic commands ###
