"""Add new flags to ServiceRequest String

Revision ID: 77ca0550e915
Revises: 8a5860249e20
Create Date: 2026-05-02 00:05:14.493357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ca0550e915'
down_revision: Union[str, Sequence[str], None] = '8a5860249e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('billing_status', sa.String(), nullable=True))
    op.add_column('service_requests', sa.Column('cc_auth_requested', sa.Boolean(), nullable=True))
    op.add_column('service_requests', sa.Column('invoice_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'invoice_deleted')
    op.drop_column('service_requests', 'cc_auth_requested')
    op.drop_column('service_requests', 'billing_status')
    # ### end Alembic commands ###
