"""Add ServiceRequestQuotation

Revision ID: 8a5860249e20
Revises: c18854c64dbf
Create Date: 2026-05-01 22:38:24.579770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5860249e20'
down_revision: Union[str, Sequence[str], None] = 'c18854c64dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_request_quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_request_id')
    )
    op.create_index(op.f('ix_service_request_quotations_id'), 'service_request_quotations', ['id'], unique=False)
    facility_columns = {
        column["name"]
        for column in sa.inspect(op.get_bind()).get_columns("facilities")
    }
    if "status" not in facility_columns:
        op.add_column(
            "facilities",
            sa.Column(
                "status",
                sa.String(),
                nullable=False,
                server_default=sa.text("'active'"),
            ),
        )
    else:
        op.alter_column('facilities', 'status',
                   existing_type=sa.VARCHAR(),
                   nullable=False,
                   existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_service_request_quotations_id'), table_name='service_request_quotations')
    op.drop_table('service_request_quotations')
    # ### end Alembic commands ###
