"""add tier fields

Revision ID: c18854c64dbf
Revises: abc123def456
Create Date: 2026-04-08 04:10:29.230123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18854c64dbf'
down_revision: Union[str, Sequence[str], None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiers', sa.Column('tier_code', sa.String(), nullable=False))
    op.add_column('tiers', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('tiers', 'response_time_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'tiers', ['tier_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tiers', type_='unique')
    op.alter_column('tiers', 'response_time_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tiers', 'status')
    op.drop_column('tiers', 'tier_code')
    # ### end Alembic commands ###
